### PR TITLE
Add support for null-values

### PR DESCRIPTION
**Pull request by fretje**
This implements null-value support for use with SqlBulkImport. 

An option "nullValue" (string) has been added as an extra argument to the 2 constructor overloads with the most arguments.
A default value of null is supplied for backwards compatibility. In that case IsDbNull will still return true when the field "IsNullOrEmpty".
When a nullValue is supplied, IsDbNull will return true when the value equals nullValue (case insensitive).
The configured "NullValue" is also exposed as a public readonly property.

### CODE REVIEW

**Comment by fretje** [comment]
Because "an empty string == DBNull" isn't always what you want.

**Comment by fletchsod-developer** [comment]
Had it been tested for performance, to make sure it doesn't slow down Bulk Insert that much?

Also, I wonder if the datatype is a string and the string is empty, does it have an option setting to become null or just empty string for Bulk Insert.  This got me thinking about character size when saving to database.  Empty string would result in bigger database then nullable string when it comes to million records.  Just a thought.

**Comment by fretje** [comment]
If you don't use it, there's no difference in behaviour.
Performance wise, there's only one more check

    if (_nullValue == null)

in IsDbNull, which shouldn't really impact performance.

The difference when you actually use the feature is that IsDbNull checks for 

    string.Equals(this[i], _nullValue, StringComparison.OrdinalIgnoreCase)

in stead of 

    string.IsNullOrEmpty(this[i])

I don't think that's much of a performance difference either. Although a case sensitive compare might be more performant. Not sure about that. Feel free to make a test case and compare it ;-)

**Comment by phatcher** [comment]
I'll have a go merging this in this weekend

**Comment by phatcher** [comment]
Done

**Pull request closed without merging**
