### PR TITLE
updated SQL Bulk Copy ColumnMappings sample code

### PR DESCRIPTION
**Pull request by ZacMarcus**

### CODE REVIEW

**Comment by phatcher** [comment]
@Zac - I've updated the readme to include the extension method I wrote for the AddColumnMapping

**Comment by ZacMarcus** [comment]
@phatcher The README still appears to be incorrect.

**Comment by phatcher** [comment]
You should be able to see the addition below...does it need anything else?

The method AddColumnMapping is an extension I wrote to simplify adding mappings to SBC

    public static class SqlBulkCopyExtensions
    {
        public static SqlBulkCopyColumnMapping AddColumnMapping(this SqlBulkCopy sbc, int sourceColumnOrdinal, int targetColumnOrdinal)
        {
            var map = new SqlBulkCopyColumnMapping(sourceColumnOrdinal, targetColumnOrdinal);
            sbc.ColumnMappings.Add(map);

            return map;
        }

        public static SqlBulkCopyColumnMapping AddColumnMapping(this SqlBulkCopy sbc, string sourceColumn, string targetColumn)
        {
            var map = new SqlBulkCopyColumnMapping(sourceColumn, targetColumn);
            sbc.ColumnMappings.Add(map);

            return map;
        }
    }

One

**Comment by ZacMarcus** [comment]
Sorry, I misread your first comment. All looks good!

**Pull request closed without merging**
